//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhDatWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public string EmployeeID { get; set; }
        public string AccountID { get; set; }
        public string BranchID { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Sex { get; set; }
        public string Position { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
